### ISSUE TITLE
Mix Can't continue due to errors on dependencies error

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#120]
```
** (Mix.Error) Can't continue due to errors on dependencies
```

A little more info at: https://github.com/elixir-lsp/elixir-ls/pull/110/files/b82d658bd86be7ed1c649601cd9bedd7e7c83764..225c5ee9ffcabb9fde0143cd7695b8b411ddad68#r377047068

This needs concrete reproduction steps.

**Comment by omar8792** [comment]
When i start vs code i get this error too: 
```
an exception was raised:
    ** (Mix.Error) Can't continue due to errors on dependencies
        (mix) lib/mix.ex:389: Mix.raise/1
        (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/tasks/loadpaths.ex:35: Mix.Tasks.Loadpaths.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/tasks/compile.ex:90: Mix.Tasks.Compile.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (language_server) lib/language_server/build.ex:164: ElixirLS.LanguageServer.Build.compile/0ElixirLS
```

elixir: 
Erlang/OTP 22 [erts-10.5.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)

erlang: 
Erlang/OTP 22 [erts-10.5.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.5.1  (abort with ^G)

running on docker container with ububtu 19.10

**Comment by axelson** [comment]
@omar8792 if you could reproduce this on a smaller project (or one an openly published project) that would be very helpful. Also does this error persist doing a `rm -rf .elixir_ls` from your project directory?

**Comment by sosodev** [comment]
FWIW updating my project's dependencies caused this issue and removing the `.elixir_ls` directory resolved it

**Comment by dogweather** [comment]
@sosodev 's solution works for me: I've been having this problem on and off.

**Comment by Sgoettschkes** [comment]
> @omar8792 if you could reproduce this on a smaller project (or one an openly published project) that would be very helpful. Also does this error persist doing a `rm -rf .elixir_ls` from your project directory?

I tried to create a setup with which this reproducible happens. On macOS with Visual Code Insider and ElixirLS 0.6.2 installed and `elixirLS.fetchDeps` disabled:

1. Create new project on the command line, using `mix new test_ls`
2. Open the project in Visual Code Insider, open `mix.ex` and open the ElixirLS Output Window
3. Add `{:phoenix, "~> 1.5.0"}` to the `deps` function to add the dependency.
4. First result: `** (Mix.Error) Can't continue due to errors on dependencies` error in ElixirLS Output
5. Run `mix deps.get` on console
6. ElixirLS compiles and errors are resolved
7. Change version of phoenix to "~> 1.4.0"
8. Second Result: `** (Mix.Error) Can't continue due to errors on dependencies` error in ElixirLS Output
9. Run `mix deps.get` on console
10. ElixirLS compiles but fails

```
== Compilation error in file lib/phoenix/endpoint/cowboy_adapter.ex ==
** (CompileError) lib/phoenix/endpoint/cowboy_adapter.ex:78: cannot import Phoenix.Endpoint.Cowboy2Adapter.info/3 because it is undefined or private
    (elixir 1.11.2) src/elixir_import.erl:64: :elixir_import.calculate/6
    (elixir 1.11.2) src/elixir_import.erl:18: :elixir_import.import/4
```

11. `mix deps.compile` on the console works fine, as expected
12. ElixirLS still reports `** (Mix.Error) Can't continue due to errors on dependencies`

I hope this helps solving this issue. It seems that adding new dependencies does not cause problems, but changing or removing does.

**Comment by thojanssens** [comment]
I have this error on my `mix.exs` file. Tried to remove `deps` and refetch dependencies, also tried to remove `.elixir_ls`, but the problem persists.

**Comment by mtrudel** [comment]
I've had success with running `MIX_ENV=test mix deps.get`. I think elixir-ls runs in a test env, so maybe that's part of the reason. 

I've also had to do this at all levels of an umbrella project (ie: run `MIX_ENV=test mix deps.get` in the root, and any sub projects whose deps have recently changed.

**Comment by lukaszsamson** [comment]
Thanks @Sgoettschkes for reliable repro steps. I was finally able to pinpoint the issue. Turns out that persistent mix state was not properly cleared and it broke dependency loading. After more than 4 years I have a fix for what was originally reported in https://github.com/JakeBecker/elixir-ls/issues/71

**Comment by sel-carlitos** [comment]
I had the same error in a brand-new project after running:

- mix phx.new . --app hello_world

The error goes away after running:

- mix deps.get
- vscode Reload Window

**Comment by miguno** [comment]
I had a very similar problem and found my way here via a Google search.

## My solution

For others reading this, here's what I needed to do:

1. Stop your IDE/editor including the elixir LSP.
2. Kill any left-over elixir/elixir-ls processes. (This was important.) Find them via e.g. `procs elixir` or `ps axu | grep elixir`.
3. In your project directory: `rm -rf .elixir_ls _build mix.lock && mix deps.get`.
4. Restart your IDE/editor including the elixir LSP.

## Environment

- elixir-ls v0.23.0
- Elixir 1.17.2 (compiled with Erlang/OTP 27)
- Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] 

## Error message

The error message I originally encountered was (first few lines):

```
[ERROR][2024-09-10 20:08:13] ...lsp/handlers.lua:623    "Process #PID<0.287.0> raised an exception\n** (Mix.Error) Can't continue due to errors on dependencies\n    (mix 1.17.2) lib/mix.ex:588: Mix.raise/2\n    (m
ix 1.17.2) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1\n    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5\n    (mix 1.17.2) lib/mix/tasks/loadpaths.ex:37: Mix.Tasks
.Loadpaths.run/1\n    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5\n    (mix 1.17.2) lib/mix/tasks/compile.ex:153: Mix.Tasks.Compile.run/1\n    (mix 1.17.2) lib/mix/task.ex:495: anonymou
s fn/3 in Mix.Task.run_task/5\n    (language_server 0.23.0) lib/language_server/build.ex:442: ElixirLS.LanguageServer.Build.run_mix_compile/1\n    (language_server 0.23.0) lib/language_server/build.ex:80: anonymou
s fn/3 in ElixirLS.LanguageServer.Build.build/3\n    (stdlib 6.0) timer.erl:590: :timer.tc/2\n    (language_server 0.23.0) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3\n
    (kernel 10.0) global.erl:699: :global.trans/4"
```

**Comment by dvlp123456** [comment]
> @omar8792 if you could reproduce this on a smaller project (or one an openly published project) that would be very helpful. Also does this error persist doing a `rm -rf .elixir_ls` from your project directory?

This is very useful to me , thank you very much. It saves me in the day.
